# Generated by Django 3.0.3 on 2020-02-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Besitzt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Zuordnung von Modulen zu den Modulkatalogen',
                'db_table': 'besitzt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fakultaet',
            fields=[
                ('fk_name', models.CharField(db_column='FK_Name', max_length=255, primary_key=True, serialize=False, verbose_name='Name der Fakultaat')),
            ],
            options={
                'verbose_name_plural': 'Fakultaeten',
                'db_table': 'fakultaet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('md_kuerzel', models.CharField(db_column='MD_Kuerzel', max_length=20, primary_key=True, serialize=False, verbose_name='Modulkuerzel')),
                ('md_abschlussziel', models.CharField(blank=True, db_column='MD_Abschlussziel', max_length=64, null=True, verbose_name='Abschlussziel')),
                ('md_name', models.CharField(blank=True, db_column='MD_Name', max_length=127, null=True, verbose_name='Name des Moduls')),
                ('md_angebotsturnus', models.CharField(blank=True, db_column='MD_Angebotsturnus', max_length=64, null=True, verbose_name='Angebotsturnus')),
                ('md_dauer', models.FloatField(blank=True, db_column='MD_Dauer', null=True, verbose_name='Dauer')),
                ('md_ects', models.IntegerField(blank=True, db_column='MD_ECTS', null=True, verbose_name='ECTS')),
                ('md_gruppengroesse', models.IntegerField(blank=True, db_column='MD_Gruppengroesse', null=True, verbose_name='Gruppengroesse')),
                ('md_inhalte', models.CharField(blank=True, db_column='MD_Inhalte', max_length=1024, null=True, verbose_name='Inhalte')),
                ('md_kompetenzziele', models.CharField(blank=True, db_column='MD_Kompetenzziele', max_length=1024, null=True, verbose_name='Kompetenzziele')),
                ('md_kontakzeit', models.IntegerField(blank=True, db_column='MD_Kontakzeit', null=True, verbose_name='Kontaktzeit')),
                ('md_lernformen', models.CharField(blank=True, db_column='MD_Lernformen', max_length=256, null=True, verbose_name='Lernformen')),
                ('md_medienform', models.CharField(blank=True, db_column='MD_Medienform', max_length=256, null=True, verbose_name='Medienform')),
                ('md_selbststudium', models.IntegerField(blank=True, db_column='MD_Selbststudium', null=True, verbose_name='Selbststudium')),
                ('md_sprache', models.CharField(blank=True, db_column='MD_Sprache', max_length=30, null=True, verbose_name='Sprache')),
                ('md_studienjahr', models.IntegerField(blank=True, db_column='MD_Studienjahr', null=True, verbose_name='Studienjahr')),
                ('md_sws', models.IntegerField(blank=True, db_column='MD_SWS', null=True, verbose_name='Semesterwochenstunden')),
                ('md_weitere_informationen', models.CharField(blank=True, db_column='MD_Weitere_Informationen', max_length=256, null=True, verbose_name='Weitere Informationen')),
            ],
            options={
                'verbose_name_plural': 'Module',
                'db_table': 'modul',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_namenskuerzel', models.CharField(db_column='P_Namenskuerzel', max_length=8, primary_key=True, serialize=False, verbose_name='Namenskuerzel')),
                ('p_vorname', models.CharField(blank=True, db_column='P_Vorname', max_length=127, null=True, verbose_name='Vorname')),
                ('p_name', models.CharField(blank=True, db_column='P_Name', max_length=127, null=True, verbose_name='Nachname')),
                ('p_telefon', models.IntegerField(blank=True, db_column='P_Telefon', null=True, verbose_name='Telefonnummer')),
                ('p_adresse_email', models.CharField(blank=True, db_column='P_Adresse_Email', max_length=127, null=True, verbose_name='E-Mail Adresse')),
                ('p_adresse_buero', models.CharField(blank=True, db_column='P_Adresse_Buero', max_length=127, null=True, verbose_name='Buero Adresse')),
                ('p_titel', models.CharField(blank=True, db_column='P_Titel', max_length=30, null=True, verbose_name='Namenszusatz')),
            ],
            options={
                'verbose_name_plural': 'Personen',
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pruefungsmodalitaet',
            fields=[
                ('pm_nr', models.AutoField(db_column='PM_Nr', primary_key=True, serialize=False, verbose_name='Pruefungsnummer')),
                ('pm_form', models.CharField(blank=True, db_column='PM_Form', max_length=40, null=True, verbose_name='Prüfungsform')),
                ('pm_benotung', models.CharField(blank=True, db_column='PM_Benotung', max_length=30, null=True, verbose_name='Benotung')),
                ('pm_vorraussetzung', models.CharField(blank=True, db_column='PM_Vorraussetzung', max_length=256, null=True, verbose_name='Pruefungsvorraussetzungen')),
                ('dauer', models.IntegerField(blank=True, db_column='Dauer', null=True, verbose_name='Pruefungsdauer')),
            ],
            options={
                'verbose_name_plural': 'Pruefungsmodalitaeten',
                'db_table': 'pruefungsmodalitaet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zusatzattribute',
            fields=[
                ('zt_name', models.CharField(db_column='ZT_Name', max_length=30, primary_key=True, serialize=False)),
                ('zt_wert', models.CharField(blank=True, db_column='ZT_Wert', max_length=256, null=True)),
                ('md_kuerzel', models.ForeignKey(blank=True, db_column='MD_Kuerzel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.Modul')),
            ],
            options={
                'verbose_name_plural': 'Zusatzattribute',
                'db_table': 'zusatzattribute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('v_nr', models.AutoField(db_column='V_Nr', primary_key=True, serialize=False)),
                ('v_sws', models.IntegerField(blank=True, db_column='V_SWS', null=True, verbose_name='Semesterwochenstunden')),
                ('v_aufwand_praesenz', models.IntegerField(blank=True, db_column='V_Aufwand_Praesenz', null=True, verbose_name='Aufwand fuer Praesenz')),
                ('v_aufwand_pruefungsvorbereitung', models.IntegerField(blank=True, db_column='V_Aufwand_Pruefungsvorbereitung', null=True, verbose_name='Aufwand für Pruefungsvorbereitung')),
                ('v_aufwand_selbststudium', models.IntegerField(blank=True, db_column='V_Aufwand_Selbststudium', null=True, verbose_name='Aufwand fuer Selbststudium')),
                ('v_ects', models.IntegerField(blank=True, db_column='V_ECTS', null=True, verbose_name='ECTS')),
                ('v_semester', models.IntegerField(blank=True, db_column='V_Semester', null=True, verbose_name='Semesterangebot')),
                ('v_titel', models.CharField(blank=True, db_column='V_Titel', max_length=60, null=True, verbose_name='Titel der Veranstaltung')),
                ('v_typ', models.CharField(blank=True, db_column='V_Typ', max_length=20, null=True, verbose_name='Typ der Veranstaltung')),
                ('md_kuerzel', models.ForeignKey(blank=True, db_column='MD_Kuerzel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.Modul')),
                ('pm_nr', models.ForeignKey(blank=True, db_column='PM_Nr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.Pruefungsmodalitaet')),
            ],
            options={
                'verbose_name_plural': 'Veranstaltungen',
                'db_table': 'veranstaltung',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Studiengang',
            fields=[
                ('sg_name', models.CharField(db_column='SG_Name', max_length=255, primary_key=True, serialize=False, verbose_name='Studiengangsname')),
                ('gehoert_zu', models.ForeignKey(db_column='gehoert_zu', on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.Fakultaet')),
            ],
            options={
                'verbose_name_plural': 'Studiengaenge',
                'db_table': 'studiengang',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulkatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_jahr', models.IntegerField(blank=True, db_column='MK_Jahr', null=True, verbose_name='Jahr')),
                ('mk_vorwort', models.CharField(blank=True, db_column='MK_Vorwort', max_length=2048, null=True, verbose_name='Vorwort')),
                ('mk_nachwort', models.CharField(blank=True, db_column='MK_Nachwort', max_length=2048, null=True, verbose_name='Nachwort')),
                ('mk_gueltig_von', models.DateField(blank=True, db_column='MK_Gueltig_von', null=True, verbose_name='Gueltig von')),
                ('mk_gueltig_bis', models.DateField(blank=True, db_column='MK_Gueltig_bis', null=True, verbose_name='Gueltig bis')),
                ('mk_module', models.ManyToManyField(through='adminpanel.Besitzt', to='adminpanel.Modul')),
                ('mk_von_studiengang', models.ForeignKey(db_column='MK_von_Studiengang', on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.Studiengang')),
            ],
            options={
                'verbose_name_plural': 'Modulkataloge',
                'db_table': 'modulkatalog',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='modul',
            name='md_lehrender',
            field=models.ManyToManyField(db_table='lehrender', null=True, related_name='lehrender', to='adminpanel.Person'),
        ),
        migrations.AddField(
            model_name='modul',
            name='md_modulverantwortlich',
            field=models.ManyToManyField(db_table='modulverantwortlicher', null=True, related_name='modulverantwortlicher', to='adminpanel.Person'),
        ),
        migrations.AddField(
            model_name='besitzt',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Modul'),
        ),
        migrations.AddField(
            model_name='besitzt',
            name='modulkatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Modulkatalog'),
        ),
    ]
