# Generated by Django 3.0.3 on 2020-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='md_voraussetzen',
            field=models.ManyToManyField(null=True, related_name='nachfolger', to='adminpanel.Modul'),
        ),
    ]
