# Generated by Django 3.0.3 on 2020-02-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_modul_md_voraussetzen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besitzt',
            name='modul',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Modul'),
        ),
        migrations.AlterField(
            model_name='besitzt',
            name='modulkatalog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Modulkatalog'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='md_voraussetzen',
            field=models.ManyToManyField(blank=True, related_name='nachfolger', to='adminpanel.Modul'),
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_module',
            field=models.ManyToManyField(blank=True, through='adminpanel.Besitzt', to='adminpanel.Modul'),
        ),
    ]
