# Generated by Django 3.0.3 on 2020-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20200226_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pruefungsmodalitaet',
            options={'managed': True, 'verbose_name_plural': 'Prüfungsmodalitaeten'},
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_gueltig_bis',
            field=models.DateField(blank=True, db_column='MK_Gueltig_bis', null=True, verbose_name='Gültig bis'),
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_gueltig_von',
            field=models.DateField(blank=True, db_column='MK_Gueltig_von', null=True, verbose_name='Gültig von'),
        ),
        migrations.AlterField(
            model_name='pruefungsmodalitaet',
            name='dauer',
            field=models.IntegerField(blank=True, db_column='Dauer', null=True, verbose_name='Prüfungsdauer'),
        ),
        migrations.AlterField(
            model_name='pruefungsmodalitaet',
            name='pm_nr',
            field=models.AutoField(db_column='PM_Nr', primary_key=True, serialize=False, verbose_name='Prüfungsnummer'),
        ),
        migrations.AlterField(
            model_name='pruefungsmodalitaet',
            name='pm_vorraussetzung',
            field=models.CharField(blank=True, db_column='PM_Vorraussetzung', max_length=256, null=True, verbose_name='Prüfungsvorraussetzungen'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='v_aufwand_praesenz',
            field=models.IntegerField(blank=True, db_column='V_Aufwand_Praesenz', null=True, verbose_name='Aufwand für Präsenz'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='v_aufwand_pruefungsvorbereitung',
            field=models.IntegerField(blank=True, db_column='V_Aufwand_Pruefungsvorbereitung', null=True, verbose_name='Aufwand für Prüfungsvorbereitung'),
        ),
    ]
