# Generated by Django 3.0.3 on 2020-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_studiengang_sg_abschluss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='md_sprache',
            field=models.CharField(blank=True, choices=[('Deutsch', 'german'), ('Englisch', 'english')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_jahr',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], db_column='MK_Jahr', null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='pruefungsmodalitaet',
            name='dauer',
            field=models.IntegerField(blank=True, choices=[(30, '30 Minuten'), (45, '45 Minuten'), (60, '60 Minuten'), (90, '90 Minuten'), (120, '120 Minuten'), (180, '180 Minuten')], db_column='Dauer', null=True, verbose_name='Prüfungsdauer'),
        ),
    ]
