# Generated by Django 3.0.3 on 2020-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20200302_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulkatalog',
            name='sg_abschluss',
        ),
        migrations.AddField(
            model_name='modulkatalog',
            name='mk_abschluss',
            field=models.CharField(choices=[('B.Sc.', 'Bachelor of Science'), ('M.Sc.', 'Master of Science'), ('B.Edu.', 'Bachelor of Education'), ('M.Edu.', 'Master of Education'), ('B.A.', 'Bachelor of Education'), ('M.A.', 'Master of Arts'), ('LL.B', 'Bachelor of Laws'), ('LL.M', 'Master of Laws')], max_length=40, null=True, verbose_name='Studienabschluss'),
        ),
    ]
