# Generated by Django 3.0.3 on 2020-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_auto_20200304_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefungsmodalitaet',
            name='dauer',
            field=models.IntegerField(blank=True, choices=[(30, '30 Minuten'), (45, '45 Minuten'), (60, '60 Minuten'), (90, '90 Minuten'), (120, '120 Minuten'), (135, '135 Minuten'), (180, '180 Minuten'), (240, '240 Minuten')], db_column='Dauer', null=True, verbose_name='Prüfungsdauer'),
        ),
    ]
