# Generated by Django 3.0.3 on 2020-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_auto_20200305_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='md_sprache',
            field=models.CharField(blank=True, choices=[('Deutsch', 'Deutsch'), ('Englisch', 'english')], max_length=30, null=True, verbose_name='Sprache'),
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_nachwort',
            field=models.TextField(blank=True, db_column='MK_Nachwort', max_length=2048, null=True, verbose_name='Nachwort'),
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_vorwort',
            field=models.TextField(blank=True, db_column='MK_Vorwort', max_length=2048, null=True, verbose_name='Vorwort'),
        ),
    ]
