# Generated by Django 3.0.3 on 2020-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_auto_20200306_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='v_titel',
            field=models.CharField(blank=True, db_column='V_Titel', max_length=200, null=True, verbose_name='Titel der Veranstaltung'),
        ),
    ]
