# Generated by Django 3.0.3 on 2020-03-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_auto_20200309_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='md_angebotsturnus',
            field=models.CharField(blank=True, choices=[('FSS', 'FSS'), ('HWS', 'HWS'), ('HWSSWS', 'HWS und SWS'), ('unregelmäßig', 'unregelmäßig')], db_column='MD_Angebotsturnus', max_length=64, null=True, verbose_name='Angebotsturnus'),
        ),
        migrations.AlterField(
            model_name='modulkatalog',
            name='mk_abschluss',
            field=models.CharField(choices=[('B.Sc.', 'Bachelor of Science'), ('M.Sc.', 'Master of Science'), ('B.Edu.', 'Bachelor of Education'), ('M.Edu.', 'Master of Education'), ('B.A.', 'Bachelor of Arts'), ('M.A.', 'Master of Arts'), ('LL.B', 'Bachelor of Laws'), ('LL.M', 'Master of Laws')], max_length=40, null=True, verbose_name='Studienabschluss'),
        ),
        migrations.AlterField(
            model_name='pruefungsmodalitaet',
            name='pm_vorraussetzung',
            field=models.TextField(blank=True, db_column='PM_Vorraussetzung', null=True, verbose_name='Prüfungsvorraussetzungen'),
        ),
    ]
