# Generated by Django 3.0.3 on 2020-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_auto_20200310_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='md_darstellung',
            field=models.CharField(blank=True, choices=[('recht', 'Recht'), ('vwl', 'Volkswirtschaftslehre'), ('bwl', 'Betriebswirtschaftslehre'), ('sowi', 'Sozialwissenschaften'), ('wifo', 'Wirtschaftsinformatik und -mathematik'), ('philo', 'Philosophie')], max_length=30, null=True, verbose_name='Darstellungsform des Moduls'),
        ),
    ]
